export const salas = [
  {
    id: "sala-informatica",
    nome: "Sala de Informática",
    grupo: [],
    imagem: "",
    posicao: { top: "", left: "" },
    descricao: "",
    quemTrabalha: [],
    quemFrequenta: [],
    oQueAcontece: [],
    charada: {
      pergunta: "",
      dica: "",
      resposta: "",
      recompensa: "",
    },
  },
  {
    id: "refeitorio",
    nome: "Refeitório",
    grupo: [],
    imagem: "",
    posicao: { top: "", left: "" },
    descricao: "",
    quemTrabalha: [],
    quemFrequenta: [],
    oQueAcontece: [],
    charada: {
      pergunta: "",
      dica: "",
      resposta: "",
      recompensa: "",
    },
  },
  {
    id: "patio",
    nome: "Pátio",
    grupo: [],
    imagem: "",
    posicao: { top: "", left: "" },
    descricao: "",
    quemTrabalha: [],
    quemFrequenta: [],
    oQueAcontece: [],
    charada: {
      pergunta: "",
      dica: "",
      resposta: "",
      recompensa: "",
    },
  },
  {
    id: "quadra",
    nome: "Quadra",
    grupo: [],
    imagem: "",
    posicao: { top: "", left: "" },
    descricao: "",
    quemTrabalha: [],
    quemFrequenta: [],
    oQueAcontece: [],
    charada: {
      pergunta: "",
      dica: "",
      resposta: "",
      recompensa: "",
    },
  },
  {
    id: "sala-professores",
    nome: "Sala dos Professores",
    grupo: [],
    imagem: "",
    posicao: { top: "", left: "" },
    descricao: "",
    quemTrabalha: [],
    quemFrequenta: [],
    oQueAcontece: [],
    charada: {
      pergunta: "",
      dica: "",
      resposta: "",
      recompensa: "",
    },
  },
  {
    id: "biblioteca",
    nome: "Biblioteca",
    grupo: [],
    imagem: "",
    posicao: { top: "", left: "" },
    descricao: "",
    quemTrabalha: [],
    quemFrequenta: [],
    oQueAcontece: [],
    charada: {
      pergunta: "",
      dica: "",
      resposta: "",
      recompensa: "",
    },
  },
  {
    id: "orientacao-convivencia",
    nome: "Sala de Orientação de Convivência",
    grupo: [],
    imagem: "",
    posicao: { top: "", left: "" },
    descricao: "",
    quemTrabalha: [],
    quemFrequenta: [],
    oQueAcontece: [],
    charada: {
      pergunta: "",
      dica: "",
      resposta: "",
      recompensa: "",
    },
  },
  {
    id: "cozinha-funcionarios",
    nome: "Cozinha dos Funcionários",
    grupo: [],
    imagem: "",
    posicao: { top: "", left: "" },
    descricao: "",
    quemTrabalha: [],
    quemFrequenta: [],
    oQueAcontece: [],
    charada: {
      pergunta: "",
      dica: "",
      resposta: "",
      recompensa: "",
    },
  },
  {
    id: "secretaria",
    nome: "Secretaria",
    grupo: [],
    imagem: "",
    posicao: { top: "", left: "" },
    descricao: "",
    quemTrabalha: [],
    quemFrequenta: [],
    oQueAcontece: [],
    charada: {
      pergunta: "",
      dica: "",
      resposta: "",
      recompensa: "",
    },
  },
  {
    id: "anfiteatro",
    nome: "Anfiteatro",
    grupo: [],
    imagem: "",
    posicao: { top: "", left: "" },
    descricao: "",
    quemTrabalha: [],
    quemFrequenta: [],
    oQueAcontece: [],
    charada: {
      pergunta: "",
      dica: "",
      resposta: "",
      recompensa: "",
    },
  },
  {
    id: "sala-de-aula",
    nome: "Sala de Aula",
    grupo: [],
    imagem: "",
    posicao: { top: "", left: "" },
    descricao: "",
    quemTrabalha: [],
    quemFrequenta: [],
    oQueAcontece: [],
    charada: {
      pergunta: "",
      dica: "",
      resposta: "",
      recompensa: "",
    },
  },
  {
    id: "laboratorio-ciencias",
    nome: "Laboratório de Ciências",
    grupo: [],
    imagem: "",
    posicao: { top: "", left: "" },
    descricao: "",
    quemTrabalha: [],
    quemFrequenta: [],
    oQueAcontece: [],
    charada: {
      pergunta: "",
      dica: "",
      resposta: "",
      recompensa: "",
    },
  },
  {
    id: "diretoria",
    nome: "Diretoria",
    grupo: [],
    imagem: "",
    posicao: { top: "", left: "" },
    descricao: "",
    quemTrabalha: [],
    quemFrequenta: [],
    oQueAcontece: [],
    charada: {
      pergunta: "",
      dica: "",
      resposta: "",
      recompensa: "",
    },
  },
  {
    id: "gremio-estudantil",
    nome: "Grêmio Estudantil",
    grupo: [],
    imagem: "",
    posicao: { top: "", left: "" },
    descricao: "",
    quemTrabalha: [],
    quemFrequenta: [],
    oQueAcontece: [],
    charada: {
      pergunta: "",
      dica: "",
      resposta: "",
      recompensa: "",
    },
  },
];
